/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Data.userData;
import Model.tableModel;
import Model.userModel;
import java.awt.Color;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class UI extends javax.swing.JFrame {
    boolean crud;
    DefaultTableModel model;
    userModel mahasiswa;
    tableModel TabelModel;
    userData data = new userData();
    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        startUp();
        colorStartUp();
        String [] defaultTable = {"NIM","NAMA","VAKSIN1","VAKSIN2","VAKSIN3","VAKSIN4","VAKSIN5"};
        model = new DefaultTableModel(defaultTable, 0);
        dataTable.setModel(model);
        
    }
    
    
    private void startUp(){
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        double width = toolkit.getScreenSize().getWidth();
        double height = toolkit.getScreenSize().getHeight();
        this.setSize((int)width, (int)height);
        dataButtonVisible(false);
        DashBoardPanel.setVisible(true);
        DataPanel.setVisible(false);
        AboutPanel.setVisible(false);
        reset();
    }
    private void colorStartUp(){
        cardVaksin1.setBorder(new LineBorder(new Color(91,124,253), 5, true));
        cardVaksin2.setBorder(new LineBorder(new Color(91,124,253), 5, true));
        cardVaksin3.setBorder(new LineBorder(new Color(91,124,253), 5, true));
        cardVaksin4.setBorder(new LineBorder(new Color(91,124,253), 5, true));
        cardVaksin5.setBorder(new LineBorder(new Color(91,124,253), 5, true));
        themeMainColor1(91,124,253);
        themeMainColor2(245,246,251);
    }
    private void themeMainColor1(int red, int green, int blue){
        //Biru gelap
        //navigasiPanel.setBackground(new Color(red, green, blue));
    }
    private void themeMainColor2(int red, int green, int blue){
        //biru terang
        mainPanel.setBackground(new Color(red, green, blue));
        DashBoardPanel.setBackground(new Color(red, green, blue));
        DataPanel.setBackground(new Color(red, green, blue));
        AboutPanel.setBackground(new Color(red, green, blue));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        DashBoardPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cardVaksin1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cardVaksin2 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cardVaksin3 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cardVaksin4 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cardVaksin5 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        DataPanel = new javax.swing.JPanel();
        namaTextField = new javax.swing.JTextField();
        nimTextField = new javax.swing.JTextField();
        vaksin1TextField = new javax.swing.JTextField();
        vaksin3TextField = new javax.swing.JTextField();
        vaksin2TextField = new javax.swing.JTextField();
        vaksin4TextField = new javax.swing.JTextField();
        vaksin5TextField = new javax.swing.JTextField();
        tabelScroll = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        simpanButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        tambahButton = new javax.swing.JButton();
        gantiButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AboutPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dashboardButton = new javax.swing.JButton();
        dataButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(196, 202, 233));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));

        mainPanel.setBackground(new java.awt.Color(245, 246, 251));
        mainPanel.setPreferredSize(new java.awt.Dimension(1366, 768));

        DashBoardPanel.setBackground(new java.awt.Color(102, 255, 102));
        DashBoardPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        DashBoardPanel.setPreferredSize(new java.awt.Dimension(1366, 714));

        usernameLabel.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        usernameLabel.setText("Pedes Official");

        welcomeLabel.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        welcomeLabel.setText("Welcome,");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/footerImage.png"))); // NOI18N

        cardVaksin1.setBackground(new java.awt.Color(231, 238, 248));
        cardVaksin1.setMaximumSize(new java.awt.Dimension(186, 100));
        cardVaksin1.setPreferredSize(new java.awt.Dimension(240, 100));

        jPanel1.setBackground(new java.awt.Color(91, 124, 253));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout cardVaksin1Layout = new javax.swing.GroupLayout(cardVaksin1);
        cardVaksin1.setLayout(cardVaksin1Layout);
        cardVaksin1Layout.setHorizontalGroup(
            cardVaksin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cardVaksin1Layout.setVerticalGroup(
            cardVaksin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardVaksin1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cardVaksin2.setBackground(new java.awt.Color(231, 238, 248));
        cardVaksin2.setMaximumSize(new java.awt.Dimension(186, 100));
        cardVaksin2.setPreferredSize(new java.awt.Dimension(240, 100));

        jPanel2.setBackground(new java.awt.Color(91, 124, 253));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout cardVaksin2Layout = new javax.swing.GroupLayout(cardVaksin2);
        cardVaksin2.setLayout(cardVaksin2Layout);
        cardVaksin2Layout.setHorizontalGroup(
            cardVaksin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cardVaksin2Layout.setVerticalGroup(
            cardVaksin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardVaksin2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cardVaksin3.setBackground(new java.awt.Color(231, 238, 248));
        cardVaksin3.setMaximumSize(new java.awt.Dimension(186, 100));
        cardVaksin3.setPreferredSize(new java.awt.Dimension(240, 100));

        jPanel3.setBackground(new java.awt.Color(91, 124, 253));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout cardVaksin3Layout = new javax.swing.GroupLayout(cardVaksin3);
        cardVaksin3.setLayout(cardVaksin3Layout);
        cardVaksin3Layout.setHorizontalGroup(
            cardVaksin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cardVaksin3Layout.setVerticalGroup(
            cardVaksin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardVaksin3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cardVaksin4.setBackground(new java.awt.Color(231, 238, 248));
        cardVaksin4.setMaximumSize(new java.awt.Dimension(186, 100));
        cardVaksin4.setPreferredSize(new java.awt.Dimension(240, 100));

        jPanel4.setBackground(new java.awt.Color(91, 124, 253));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout cardVaksin4Layout = new javax.swing.GroupLayout(cardVaksin4);
        cardVaksin4.setLayout(cardVaksin4Layout);
        cardVaksin4Layout.setHorizontalGroup(
            cardVaksin4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cardVaksin4Layout.setVerticalGroup(
            cardVaksin4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardVaksin4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cardVaksin5.setBackground(new java.awt.Color(231, 238, 248));
        cardVaksin5.setMaximumSize(new java.awt.Dimension(186, 100));
        cardVaksin5.setPreferredSize(new java.awt.Dimension(240, 100));

        jPanel5.setBackground(new java.awt.Color(91, 124, 253));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout cardVaksin5Layout = new javax.swing.GroupLayout(cardVaksin5);
        cardVaksin5.setLayout(cardVaksin5Layout);
        cardVaksin5Layout.setHorizontalGroup(
            cardVaksin5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cardVaksin5Layout.setVerticalGroup(
            cardVaksin5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardVaksin5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout DashBoardPanelLayout = new javax.swing.GroupLayout(DashBoardPanel);
        DashBoardPanel.setLayout(DashBoardPanelLayout);
        DashBoardPanelLayout.setHorizontalGroup(
            DashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashBoardPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usernameLabel)
                .addContainerGap(849, Short.MAX_VALUE))
            .addGroup(DashBoardPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(DashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardVaksin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardVaksin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardVaksin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DashBoardPanelLayout.createSequentialGroup()
                        .addGroup(DashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cardVaksin4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cardVaksin5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))))
        );
        DashBoardPanelLayout.setVerticalGroup(
            DashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashBoardPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(DashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomeLabel)
                    .addComponent(usernameLabel))
                .addGap(26, 26, 26)
                .addComponent(cardVaksin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cardVaksin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cardVaksin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cardVaksin4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cardVaksin5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashBoardPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        DataPanel.setBackground(new java.awt.Color(255, 51, 255));
        DataPanel.setPreferredSize(new java.awt.Dimension(1366, 714));

        namaTextField.setText("NAMA");
        namaTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namaTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                namaTextFieldFocusLost(evt);
            }
        });

        nimTextField.setText("NIM");
        nimTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nimTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nimTextFieldFocusLost(evt);
            }
        });

        vaksin1TextField.setText("VAKSIN 1");
        vaksin1TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vaksin1TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                vaksin1TextFieldFocusLost(evt);
            }
        });

        vaksin3TextField.setText("VAKSIN 3");
        vaksin3TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vaksin3TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                vaksin3TextFieldFocusLost(evt);
            }
        });

        vaksin2TextField.setText("VAKSIN 2");
        vaksin2TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vaksin2TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                vaksin2TextFieldFocusLost(evt);
            }
        });

        vaksin4TextField.setText("VAKSIN 4");
        vaksin4TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vaksin4TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                vaksin4TextFieldFocusLost(evt);
            }
        });

        vaksin5TextField.setText("VAKSIN 5");
        vaksin5TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vaksin5TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                vaksin5TextFieldFocusLost(evt);
            }
        });

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "NAMA", "VAKSIN 1", "VAKSIN 2", "VAKSIN 3", "VAKSIN 4", "VAKSIN 5"
            }
        ));
        dataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataTableMouseClicked(evt);
            }
        });
        tabelScroll.setViewportView(dataTable);

        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        tambahButton.setText("Tambah");
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });

        gantiButton.setText("Ganti");
        gantiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gantiButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/footerImage2.jpg"))); // NOI18N

        javax.swing.GroupLayout DataPanelLayout = new javax.swing.GroupLayout(DataPanel);
        DataPanel.setLayout(DataPanelLayout);
        DataPanelLayout.setHorizontalGroup(
            DataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataPanelLayout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(DataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gantiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaTextField)
                    .addComponent(nimTextField)
                    .addComponent(vaksin1TextField)
                    .addComponent(vaksin2TextField)
                    .addComponent(vaksin3TextField)
                    .addComponent(vaksin4TextField)
                    .addComponent(vaksin5TextField)
                    .addComponent(simpanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tambahButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(DataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabelScroll))
                .addGap(36, 36, 36))
        );
        DataPanelLayout.setVerticalGroup(
            DataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DataPanelLayout.createSequentialGroup()
                        .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(vaksin1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vaksin2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vaksin3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vaksin4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vaksin5TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(simpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tambahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gantiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(DataPanelLayout.createSequentialGroup()
                        .addComponent(tabelScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        AboutPanel.setMinimumSize(new java.awt.Dimension(1082, 747));
        AboutPanel.setName(""); // NOI18N
        AboutPanel.setPreferredSize(new java.awt.Dimension(1366, 714));
        AboutPanel.setRequestFocusEnabled(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/aboutImage.png"))); // NOI18N

        javax.swing.GroupLayout AboutPanelLayout = new javax.swing.GroupLayout(AboutPanel);
        AboutPanel.setLayout(AboutPanelLayout);
        AboutPanelLayout.setHorizontalGroup(
            AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutPanelLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        AboutPanelLayout.setVerticalGroup(
            AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutPanelLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        dashboardButton.setText("Dashboard");
        dashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardButtonActionPerformed(evt);
            }
        });

        dataButton.setText("Data");
        dataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataButtonActionPerformed(evt);
            }
        });

        aboutButton.setText("About");
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(441, 441, 441)
                .addComponent(dashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(aboutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DashBoardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AboutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aboutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(DashBoardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(AboutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 715, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButtonActionPerformed
        dataButtonVisible(false);
        DashBoardPanel.setVisible(true);
        DataPanel.setVisible(false);
        AboutPanel.setVisible(false);
    }//GEN-LAST:event_dashboardButtonActionPerformed

    private void dataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataButtonActionPerformed
        dataButtonVisible(true);
        DashBoardPanel.setVisible(false);
        DataPanel.setVisible(true);
        AboutPanel.setVisible(false);
        displayDataMahasiswa();
    }//GEN-LAST:event_dataButtonActionPerformed

    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed
        DashBoardPanel.setVisible(false);
        DataPanel.setVisible(false);
        AboutPanel.setVisible(true);
        dataButtonVisible(false);
    }//GEN-LAST:event_aboutButtonActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        TabelModel = new tableModel();
        mahasiswa = new userModel();
        if (nimTextField.getText().equals(TabelModel.getNIM()) || namaTextField.getText().equals(TabelModel.getNAMA()) ){
            JOptionPane.showMessageDialog(this, "Masukkan NIM atau Nama terlebih dahulu");
        }else{
            mahasiswa.setNIM(nimTextField.getText());
            mahasiswa.setNama(namaTextField.getText());
        }
        if (vaksin1TextField.getText().equals(TabelModel.getVAKSIN1())) {mahasiswa.setVaksin1("-");}else{mahasiswa.setVaksin1(vaksin1TextField.getText());}
        if (vaksin2TextField.getText().equals(TabelModel.getVAKSIN2())) {mahasiswa.setVaksin2("-");}else{mahasiswa.setVaksin2(vaksin2TextField.getText());}
        if (vaksin3TextField.getText().equals(TabelModel.getVAKSIN3())) {mahasiswa.setVaksin3("-");}else{mahasiswa.setVaksin3(vaksin3TextField.getText());}
        if (vaksin4TextField.getText().equals(TabelModel.getVAKSIN4())) {mahasiswa.setVaksin4("-");}else{mahasiswa.setVaksin4(vaksin4TextField.getText());}
        if (vaksin5TextField.getText().equals(TabelModel.getVAKSIN5())) {mahasiswa.setVaksin5("-");}else{mahasiswa.setVaksin5(vaksin5TextField.getText());}
        
        if (data.simpanDataMahasiswa(mahasiswa)) {
            JOptionPane.showMessageDialog(this, "Sukses Menambah Data");
            displayDataMahasiswa();
            reset();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal Menambah Data");
        }
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin menghapus data ini?","Delete Mahasiswa",0)==0){
            mahasiswa = new userModel();
            mahasiswa.setNIM(nimTextField.getText());
            if (data.hapusDataMahasiswa(mahasiswa)) {
                JOptionPane.showMessageDialog(this, "Sukses Menghapus Data");
                displayDataMahasiswa();
                reset();
            }else{
                JOptionPane.showMessageDialog(this, "Gagal Menghapus Data");
            }
        }
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        displayDataMahasiswa();
        reset();
    }//GEN-LAST:event_tambahButtonActionPerformed

    private void gantiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gantiButtonActionPerformed
        mahasiswa = new userModel();
        mahasiswa.setNIM(nimTextField.getText());
        mahasiswa.setNama(namaTextField.getText());
        mahasiswa.setVaksin1(vaksin1TextField.getText());
        mahasiswa.setVaksin2(vaksin2TextField.getText());
        mahasiswa.setVaksin3(vaksin3TextField.getText());
        mahasiswa.setVaksin4(vaksin4TextField.getText());
        mahasiswa.setVaksin5(vaksin5TextField.getText());
        if (data.gantiDataMahasiswa(mahasiswa)) {
            JOptionPane.showMessageDialog(this, "Berhasil Ganti Data");
            displayDataMahasiswa();
            reset();
        }else{
            JOptionPane.showMessageDialog(this, "Gagal Ganti Data");
        }
    }//GEN-LAST:event_gantiButtonActionPerformed

    private void dataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataTableMouseClicked
        int row = dataTable.getSelectedRow();
        nimTextField.setText(dataTable.getValueAt(row, 0).toString());
        namaTextField.setText(dataTable.getValueAt(row, 1).toString());
        vaksin1TextField.setText(dataTable.getValueAt(row, 2).toString());
        vaksin2TextField.setText(dataTable.getValueAt(row, 3).toString());
        vaksin3TextField.setText(dataTable.getValueAt(row, 4).toString());
        vaksin4TextField.setText(dataTable.getValueAt(row, 5).toString());
        vaksin5TextField.setText(dataTable.getValueAt(row, 6).toString());
        nimTextField.setForeground(new Color(0,0,0));
        namaTextField.setForeground(new Color(0,0,0));
        vaksin1TextField.setForeground(new Color(0,0,0));
        vaksin2TextField.setForeground(new Color(0,0,0));
        vaksin3TextField.setForeground(new Color(0,0,0));
        vaksin4TextField.setForeground(new Color(0,0,0));
        vaksin5TextField.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_dataTableMouseClicked

    private void nimTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nimTextFieldFocusGained
        if(nimTextField.getText().equals(TabelModel.getNIM())){
            nimTextField.setText("");
            nimTextField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_nimTextFieldFocusGained

    private void namaTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaTextFieldFocusGained
        if(namaTextField.getText().equals(TabelModel.getNAMA())){
            namaTextField.setText("");
            namaTextField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_namaTextFieldFocusGained

    private void vaksin1TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vaksin1TextFieldFocusGained
        if(vaksin1TextField.getText().equals(TabelModel.getVAKSIN1())){
            vaksin1TextField.setText("");
            vaksin1TextField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_vaksin1TextFieldFocusGained

    private void vaksin2TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vaksin2TextFieldFocusGained
        if(vaksin2TextField.getText().equals(TabelModel.getVAKSIN2())){
            vaksin2TextField.setText("");
            vaksin2TextField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_vaksin2TextFieldFocusGained

    private void vaksin3TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vaksin3TextFieldFocusGained
        if(vaksin3TextField.getText().equals(TabelModel.getVAKSIN3())){
            vaksin3TextField.setText("");
            vaksin3TextField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_vaksin3TextFieldFocusGained

    private void vaksin4TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vaksin4TextFieldFocusGained
        if(vaksin4TextField.getText().equals(TabelModel.getVAKSIN4())){
            vaksin4TextField.setText("");
            vaksin4TextField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_vaksin4TextFieldFocusGained

    private void vaksin5TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vaksin5TextFieldFocusGained
        if(vaksin5TextField.getText().equals(TabelModel.getVAKSIN5())){
            vaksin5TextField.setText("");
            vaksin5TextField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_vaksin5TextFieldFocusGained

    private void nimTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nimTextFieldFocusLost
        if(nimTextField.getText().equals("")){
            nimTextField.setText(TabelModel.getNIM());
            nimTextField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_nimTextFieldFocusLost

    private void namaTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaTextFieldFocusLost
        if(namaTextField.getText().equals("")){
            namaTextField.setText(TabelModel.getNAMA());
            namaTextField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_namaTextFieldFocusLost

    private void vaksin1TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vaksin1TextFieldFocusLost
        if(vaksin1TextField.getText().equals("")){
            vaksin1TextField.setText(TabelModel.getVAKSIN1());
            vaksin1TextField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_vaksin1TextFieldFocusLost

    private void vaksin2TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vaksin2TextFieldFocusLost
        if(vaksin2TextField.getText().equals("")){
            vaksin2TextField.setText(TabelModel.getVAKSIN2());
            vaksin2TextField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_vaksin2TextFieldFocusLost

    private void vaksin3TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vaksin3TextFieldFocusLost
        if(vaksin3TextField.getText().equals("")){
            vaksin3TextField.setText(TabelModel.getVAKSIN3());
            vaksin3TextField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_vaksin3TextFieldFocusLost

    private void vaksin4TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vaksin4TextFieldFocusLost
        if(vaksin4TextField.getText().equals("")){
            vaksin4TextField.setText(TabelModel.getVAKSIN4());
            vaksin4TextField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_vaksin4TextFieldFocusLost

    private void vaksin5TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vaksin5TextFieldFocusLost
        if(vaksin5TextField.getText().equals("")){
            vaksin5TextField.setText(TabelModel.getVAKSIN5());
            vaksin5TextField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_vaksin5TextFieldFocusLost
    private void dataButtonVisible(boolean crud){
        simpanButton.setVisible(crud);
        hapusButton.setVisible(crud);
        tambahButton.setVisible(crud);
        gantiButton.setVisible(crud);
        tabelScroll.setVisible(crud);
        namaTextField.setVisible(crud);
        nimTextField.setVisible(crud);
        vaksin1TextField.setVisible(crud);
        vaksin2TextField.setVisible(crud);
        vaksin3TextField.setVisible(crud);
        vaksin4TextField.setVisible(crud);
        vaksin5TextField.setVisible(crud);
    }


    private void displayDataMahasiswa(){
        List<userModel> ls = new ArrayList<userModel>();
        ls = new userData().getAll();
        String DataMahasiswa[][] = new String[ls.size()][7];
        for (int i = 0; i < ls.size(); i++) {
            DataMahasiswa[i][0] = ls.get(i).getNIM();
            DataMahasiswa[i][1] = ls.get(i).getNama();
            DataMahasiswa[i][2] = ls.get(i).getVaksin1();
            DataMahasiswa[i][3] = ls.get(i).getVaksin2();
            DataMahasiswa[i][4] = ls.get(i).getVaksin3();
            DataMahasiswa[i][5] = ls.get(i).getVaksin4();
            DataMahasiswa[i][6] = ls.get(i).getVaksin5();
        }
        dataTable.setModel(new DefaultTableModel(DataMahasiswa, new String[]{"NIM","NAMA","VAKSIN1","VAKSIN2","VAKSIN3","VAKSIN4","VAKSIN5"}));
    }
    private void reset(){
        TabelModel = new tableModel();
        nimTextField.setText(TabelModel.getNIM());
        namaTextField.setText(TabelModel.getNAMA());
        vaksin1TextField.setText(TabelModel.getVAKSIN1());
        vaksin2TextField.setText(TabelModel.getVAKSIN2());
        vaksin3TextField.setText(TabelModel.getVAKSIN3());
        vaksin4TextField.setText(TabelModel.getVAKSIN4());
        vaksin5TextField.setText(TabelModel.getVAKSIN5());
        nimTextField.setForeground(new Color(153,153,153));
        namaTextField.setForeground(new Color(153,153,153));
        vaksin1TextField.setForeground(new Color(153,153,153));
        vaksin2TextField.setForeground(new Color(153,153,153));
        vaksin3TextField.setForeground(new Color(153,153,153));
        vaksin4TextField.setForeground(new Color(153,153,153));
        vaksin5TextField.setForeground(new Color(153,153,153));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutPanel;
    private javax.swing.JPanel DashBoardPanel;
    private javax.swing.JPanel DataPanel;
    private javax.swing.JButton aboutButton;
    private javax.swing.JPanel cardVaksin1;
    private javax.swing.JPanel cardVaksin2;
    private javax.swing.JPanel cardVaksin3;
    private javax.swing.JPanel cardVaksin4;
    private javax.swing.JPanel cardVaksin5;
    private javax.swing.JButton dashboardButton;
    private javax.swing.JButton dataButton;
    private javax.swing.JTable dataTable;
    private javax.swing.JButton gantiButton;
    private javax.swing.JButton hapusButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JButton simpanButton;
    private javax.swing.JScrollPane tabelScroll;
    private javax.swing.JButton tambahButton;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField vaksin1TextField;
    private javax.swing.JTextField vaksin2TextField;
    private javax.swing.JTextField vaksin3TextField;
    private javax.swing.JTextField vaksin4TextField;
    private javax.swing.JTextField vaksin5TextField;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
